### ISSUE TITLE
Placeholder for minor refactoring tasks

### ISSUE THREAD

**Issue by nazaryan** [nazaryan/ShipIt#3]
- [ ] Remove the final keyword from method arguments and local variables. Of course keep the static finals as is.
- [ ] private static instead of static private. 
- [ ] keep the fields of a class at the top of the class definition, not at the bottom.
- [x] ~~Define inner classes such as CustomCollectionEditor with a class definition, as opposed to anonymously. This improves readability during debug. Otherwise the type is simply shown as e.g. ShippingController$1.~~
- [ ] write idToItemMapping = new TreeMap<>(); as opposed to idToItemMapping = new TreeMap<Long, VolumeCountPair>();
- [ ] com.nkwebapps.shipit.repository.RoleRepository: Missing white space before class definition opening bracket.
- [ ] com.nkwebapps.shipit.service.StorageItemService: Missing white space between keyword if and opening bracket, in method changeStorageItemCount.
- [ ] com.nkwebapps.shipit.service.ShippingService: Missing white space between keyword for and opening bracket, in method getShippings.

**Comment by haykart** [comment]
I will mark 4th subtask as "Invalid", becasue even if it helps during debugging, it reduces code readability. Overall first priority is to write human-readable code, not debug-readable.
